# **Análise de Sentimentos**

## **Importação das bibliotecas e leitura dos dados**

In [9]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import numpy as np

In [10]:
avaliacoes = pd.read_parquet("../data/processed/avaliacoes.parquet")

## **Função para classificar sentimentos**

Essa função classifica os sentimentos com base nos scores de polaridade gerados pelos modelos, atribuindo rótulos como "Muito Positivo", "Positivo", "Neutro", "Negativo" ou "Muito Negativo".

In [11]:
def classificar_sentimento(score):
    if score >= 0.75: return 'Muito Positivo'
    elif score >= 0.25: return 'Positivo'
    elif score > -0.25: return 'Neutro'
    elif score >= -0.75: return 'Negativo'
    else: return 'Muito Negativo'

## **Aplicação dos modelos de análise de sentimentos**

Nessa seção, aplicamos os modelos Vader, leIA e TextBlob para analisar os sentimentos expressos nos comentários da base de dados. Todos os modelos devolvem scores de polaridade, ou seja, valores numéricos que indicam a intensidade do sentimento presente em cada comentário. Para todos, o intervalo de polaridade varia de -1 a 1, onde -1 representa um sentimento extremamente negativo, 0 representa um sentimento neutro e 1 representa um sentimento extremamente positivo. Após obter os scores de polaridade, utilizamos a função de classificação para categorizar os sentimentos em rótulos compreensíveis, facilitando a interpretação dos resultados.

### **Vader**

In [12]:
from vaderSentiment.vaderSentiment import SentimentIntensityAnalyzer

In [13]:
vader = SentimentIntensityAnalyzer()
avaliacoes['vader_score'] = avaliacoes['review_comment'].apply(lambda x: vader.polarity_scores(str(x))['compound'])
avaliacoes['vader_label'] = avaliacoes['vader_score'].apply(classificar_sentimento)
display(avaliacoes.head(10))

,review_score,review_comment,review_label,vader_score,vader_label
0,5,recebi bem antes do prazo estipulado,Muito Positivo,0.0000,Neutro
1,5,parabéns lojas lannister adorei comprar pela ...,Muito Positivo,0.0000,Neutro
2,4,recomendo aparelho eficiente no site a marca d...,Positivo,-0.2960,Negativo
3,4,mas um pouco travandopelo valor ta boa\r\n,Positivo,0.0000,Neutro
4,5,super recomendo vendedor confiável produto ok ...,Muito Positivo,0.7269,Positivo
5,2,gostaria de saber o que houve sempre recebi e...,Negativo,0.0000,Neutro
6,1,não chegou meu produto péssimo,Muito Negativo,0.0000,Neutro
7,5,ótimo loja nota 10,Muito Positivo,0.0000,Neutro
8,5,obrigado pela atençao amim dispensada,Muito Positivo,0.0000,Neutro
9,5,a compra foi realizada facilmente\r\na entreg...,Muito Positivo,0.0000,Neutro

### **LeIA**

In [14]:
from leia import SentimentIntensityAnalyzer

In [15]:
leia = SentimentIntensityAnalyzer()
avaliacoes['leia_score'] = avaliacoes['review_comment'].apply(lambda x: leia.polarity_scores(str(x))['compound'])
avaliacoes['leia_label'] = avaliacoes['leia_score'].apply(classificar_sentimento)
display(avaliacoes.head(10))

,review_score,review_comment,review_label,vader_score,vader_label,leia_score,leia_label
0,5,recebi bem antes do prazo estipulado,Muito Positivo,0.0000,Neutro,0.2732,Positivo
1,5,parabéns lojas lannister adorei comprar pela ...,Muito Positivo,0.0000,Neutro,0.9413,Muito Positivo
2,4,recomendo aparelho eficiente no site a marca d...,Positivo,-0.2960,Negativo,0.6486,Positivo
3,4,mas um pouco travandopelo valor ta boa\r\n,Positivo,0.0000,Neutro,0.7264,Positivo
4,5,super recomendo vendedor confiável produto ok ...,Muito Positivo,0.7269,Positivo,0.8979,Muito Positivo
5,2,gostaria de saber o que houve sempre recebi e...,Negativo,0.0000,Neutro,0.0000,Neutro
6,1,não chegou meu produto péssimo,Muito Negativo,0.0000,Neutro,-0.2960,Negativo
7,5,ótimo loja nota 10,Muito Positivo,0.0000,Neutro,0.3612,Positivo
8,5,obrigado pela atençao amim dispensada,Muito Positivo,0.0000,Neutro,0.1280,Neutro
9,5,a compra foi realizada facilmente\r\na entreg...,Muito Positivo,0.0000,Neutro,0.6249,Positivo

### **TextBlob**

In [16]:
from textblob import TextBlob

In [17]:
avaliacoes['textblob_score'] = avaliacoes['review_comment'].apply(lambda x: TextBlob(str(x)).sentiment.polarity)
avaliacoes['textblob_label'] = avaliacoes['textblob_score'].apply(classificar_sentimento)
display(avaliacoes.head(10))

,review_score,review_comment,review_label,vader_score,vader_label,leia_score,leia_label,textblob_score,textblob_label
0,5,recebi bem antes do prazo estipulado,Muito Positivo,0.0000,Neutro,0.2732,Positivo,0.000000,Neutro
1,5,parabéns lojas lannister adorei comprar pela ...,Muito Positivo,0.0000,Neutro,0.9413,Muito Positivo,0.000000,Neutro
2,4,recomendo aparelho eficiente no site a marca d...,Positivo,-0.2960,Negativo,0.6486,Positivo,0.000000,Neutro
3,4,mas um pouco travandopelo valor ta boa\r\n,Positivo,0.0000,Neutro,0.7264,Positivo,0.000000,Neutro
4,5,super recomendo vendedor confiável produto ok ...,Muito Positivo,0.7269,Positivo,0.8979,Muito Positivo,0.416667,Positivo
5,2,gostaria de saber o que houve sempre recebi e...,Negativo,0.0000,Neutro,0.0000,Neutro,0.000000,Neutro
6,1,não chegou meu produto péssimo,Muito Negativo,0.0000,Neutro,-0.2960,Negativo,0.000000,Neutro
7,5,ótimo loja nota 10,Muito Positivo,0.0000,Neutro,0.3612,Positivo,0.000000,Neutro
8,5,obrigado pela atençao amim dispensada,Muito Positivo,0.0000,Neutro,0.1280,Neutro,0.000000,Neutro
9,5,a compra foi realizada facilmente\r\na entreg...,Muito Positivo,0.0000,Neutro,0.6249,Positivo,0.000000,Neutro

## **Exportação dos resultados**

In [18]:
# avaliacoes.to_parquet("resultados.parquet", index=False)