# **Análise de Sentimentos**

## Importação das bibliotecas e leitura dos dados

In [2]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import numpy as np

In [3]:
avaliacoes = pd.read_parquet("../data/processed/avaliacoes.parquet")

## Funcão para classificar sentimentos

In [4]:
def classificar_sentimento(score):
    if score >= 0.75: return 'Muito Positivo'
    elif score >= 0.25: return 'Positivo'
    elif score > -0.25: return 'Neutro'
    elif score >= -0.75: return 'Negativo'
    else: return 'Muito Negativo'

## Vader

In [5]:
from vaderSentiment.vaderSentiment import SentimentIntensityAnalyzer

In [6]:
vader = SentimentIntensityAnalyzer()
avaliacoes['vader_score'] = avaliacoes['review_comment'].apply(lambda x: vader.polarity_scores(str(x))['compound'])
avaliacoes['vader_label'] = avaliacoes['vader_score'].apply(classificar_sentimento)
display(avaliacoes.head(10))

,review_score,review_comment,review_label,vader_score,vader_label
0,5,recebi bem antes do prazo estipulado,Muito Positivo,0.0000,Neutro
1,5,parabéns lojas lannister adorei comprar pela ...,Muito Positivo,0.0000,Neutro
2,4,recomendo aparelho eficiente no site a marca d...,Positivo,-0.2960,Negativo
3,4,mas um pouco travandopelo valor ta boa\r\n,Positivo,0.0000,Neutro
4,5,super recomendo vendedor confiável produto ok ...,Muito Positivo,0.7269,Positivo
5,2,gostaria de saber o que houve sempre recebi e...,Negativo,0.0000,Neutro
6,1,não chegou meu produto péssimo,Muito Negativo,0.0000,Neutro
7,5,ótimo loja nota 10,Muito Positivo,0.0000,Neutro
8,5,obrigado pela atençao amim dispensada,Muito Positivo,0.0000,Neutro
9,5,a compra foi realizada facilmente\r\na entreg...,Muito Positivo,0.0000,Neutro

## LeIA

In [ ]:
from LeIA import SentimentIntensityAnalyzer

In [ ]:
leia = SentimentIntensityAnalyzer()
avaliacoes['leia_score'] = avaliacoes['review_comment'].apply(lambda x: leia.polarity_scores(str(x))['compound'])
avaliacoes['leia_label'] = avaliacoes['leia_score'].apply(classificar_sentimento)
display(avaliacoes.head(10))

,review_score,review_comment,vader_score,vader_label,textblob_score,textblob_label,leia_score,leia_label
0,5,recebi bem antes do prazo estipulado,0.0000,Neutro,0.000000,Neutro,0.0000,Neutro
1,5,parabéns lojas lannister adorei comprar pela ...,0.0000,Neutro,0.000000,Neutro,0.0000,Neutro
2,4,recomendo aparelho eficiente no site a marca d...,-0.2960,Negativo,0.000000,Neutro,-0.2960,Negativo
3,4,mas um pouco travandopelo valor ta boa\r\n,0.0000,Neutro,0.000000,Neutro,0.0000,Neutro
4,5,super recomendo vendedor confiável produto ok ...,0.7269,Positivo,0.416667,Positivo,0.7269,Positivo
5,2,gostaria de saber o que houve sempre recebi e...,0.0000,Neutro,0.000000,Neutro,0.0000,Neutro
6,1,não chegou meu produto péssimo,0.0000,Neutro,0.000000,Neutro,0.0000,Neutro
7,5,ótimo loja nota 10,0.0000,Neutro,0.000000,Neutro,0.0000,Neutro
8,5,obrigado pela atençao amim dispensada,0.0000,Neutro,0.000000,Neutro,0.0000,Neutro
9,5,a compra foi realizada facilmente\r\na entreg...,0.0000,Neutro,0.000000,Neutro,0.0000,Neutro

## TextBlob

In [ ]:
from textblob import TextBlob

In [ ]:
avaliacoes['textblob_score'] = avaliacoes['review_comment'].apply(lambda x: TextBlob(str(x)).sentiment.polarity)
avaliacoes['textblob_label'] = avaliacoes['textblob_score'].apply(classificar_sentimento)
display(avaliacoes.head(10))

,review_score,review_comment,vader_score,vader_label,textblob_score,textblob_label
0,5,recebi bem antes do prazo estipulado,0.0000,Neutro,0.000000,Neutro
1,5,parabéns lojas lannister adorei comprar pela ...,0.0000,Neutro,0.000000,Neutro
2,4,recomendo aparelho eficiente no site a marca d...,-0.2960,Negativo,0.000000,Neutro
3,4,mas um pouco travandopelo valor ta boa\r\n,0.0000,Neutro,0.000000,Neutro
4,5,super recomendo vendedor confiável produto ok ...,0.7269,Positivo,0.416667,Positivo
5,2,gostaria de saber o que houve sempre recebi e...,0.0000,Neutro,0.000000,Neutro
6,1,não chegou meu produto péssimo,0.0000,Neutro,0.000000,Neutro
7,5,ótimo loja nota 10,0.0000,Neutro,0.000000,Neutro
8,5,obrigado pela atençao amim dispensada,0.0000,Neutro,0.000000,Neutro
9,5,a compra foi realizada facilmente\r\na entreg...,0.0000,Neutro,0.000000,Neutro

## Exportação dos resultados

In [ ]:
# avaliacoes.to_parquet("resultados.parquet", index=False)